/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ioncannon_com_qboost_QboostService */

#ifndef _Included_ioncannon_com_qboost_QboostService
#define _Included_ioncannon_com_qboost_QboostService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ioncannon_com_qboost_QboostService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ioncannon_com_qboost_QboostService_init
  (JNIEnv *, jobject);

/*
 * Class:     ioncannon_com_qboost_QboostService
 * Method:    setMode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_ioncannon_com_qboost_QboostService_setMode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ioncannon_com_qboost_QboostService
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ioncannon_com_qboost_QboostService_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
